### ISSUE TITLE
Can not install with Laravel 10.15

### ISSUE THREAD

**Issue by shoaibsharif** [agence104/livekit-server-sdk-php#10]
I am trying to install this package in laravel 10 and I am getting this error
```bash
❯ composer require agence104/livekit-server-sdk
./composer.json has been updated
Running composer update agence104/livekit-server-sdk
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - twirp/twirp v0.8.1 requires psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - agence104/livekit-server-sdk[1.0.0, ..., 1.1.0] require twirp/twirp ^0.8.1 -> satisfiable by twirp/twirp[v0.8.1].
    - Root composer.json requires agence104/livekit-server-sdk * -> satisfiable by agence104/livekit-server-sdk[1.0.0, 1.0.1, 1.1.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require agence104/livekit-server-sdk:*" to figure out if any version is installable, or "composer require agence104/livekit-server-sdk:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.


```

**Comment by enayatinfo** [comment]
> I am trying to install this package in laravel 10 and I am getting this error
> 
> ```shell
> ❯ composer require agence104/livekit-server-sdk
> ./composer.json has been updated
> Running composer update agence104/livekit-server-sdk
> Loading composer repositories with package information
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - twirp/twirp v0.8.1 requires psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
>     - agence104/livekit-server-sdk[1.0.0, ..., 1.1.0] require twirp/twirp ^0.8.1 -> satisfiable by twirp/twirp[v0.8.1].
>     - Root composer.json requires agence104/livekit-server-sdk * -> satisfiable by agence104/livekit-server-sdk[1.0.0, 1.0.1, 1.1.0].
> 
> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
> You can also try re-running composer require with an explicit version constraint, e.g. "composer require agence104/livekit-server-sdk:*" to figure out if any version is installable, or "composer require agence104/livekit-server-sdk:^2.1" if you know which you need.
> 
> Installation failed, reverting ./composer.json and ./composer.lock to their original content.
> ```

If your dependencies don't need http-message V2 Use:
` composer install -W ...`
check dependencies requirements in composer.lock file
