### ISSUE TITLE
Unable to set AutoEgress while creating new room 

### ISSUE THREAD

**Issue by hazhayder** [agence104/livekit-server-sdk-php#14]
I am trying to set AutoEgress while creating room I am using docker-compose to deploy livekit on VPS, below is the code snippet and the output is attached below 
![code-snapshot](https://github.com/agence104/livekit-server-sdk-php/assets/12206002/d5d72331-d24e-493b-a238-549d84872276)
![image](https://github.com/agence104/livekit-server-sdk-php/assets/12206002/dba62868-a088-4fc6-8f5d-d2793db9f8d2)

**Comment by shakaran** [comment]
@hazhayder could you copy and paste the code or attach the file for run easy from the code? It is hard to debug this if the mantainer has to write every line in the image

**Comment by hazhayder** [comment]
> @hazhayder could you copy and paste the code or attach the file for run easy from the code? It is hard to debug this if the mantainer has to write every line in the image

`public function attempt(string $token)
    {
        $s3Upload = (new S3Upload())->setAccessKey("HasnainHaider")->setSecret("HasnainHaider")->setEndpoint("https://minio.exodevs.com")->setBucket("livekit")->setRegion("");
        $roomServiceClient = new RoomServiceClient(env('LIVEKIT_HOST'), env('LIVEKIT_API_KEY'), env('LIVEKIT_API_SECRET'));
        $newRoomOptions = new RoomCreateOptions();
        $roomEgress = new RoomEgress();
        $autoTrackEgress = new AutoTrackEgress();
        $autoTrackEgress = $autoTrackEgress->setS3($s3Upload)->setFilepath("livekit/{room_name}-{publisher_identity}-{time}");
        $roomEgress = $roomEgress->setTracks($autoTrackEgress);
        $newRoomOptions = $newRoomOptions->setEgress($roomEgress);
        $newRoomOptions = $newRoomOptions->setName("HasnainNewRoom");
        // dd($newRoomOptions);
        $roomServiceClient->createRoom($newRoomOptions);

        $rooms = $roomServiceClient->listRooms();
        // dd($rooms->getRooms());
        $egressClient = new EgressServiceClient(env('LIVEKIT_HOST'), env('LIVEKIT_API_KEY'), env('LIVEKIT_API_SECRET'));
        $outputConfig = new EncodedFileOutput();

        // $outputConfig = $outputConfig->setFileType(EncodedFileType::MP4)
            // ->setFilepath("livekit-demo/room-composite-test.mp4");
            // ->setS3($s3Upload);
        // $outputConfiguration.setFileF
        // $response = $egressClient->startRoomCompositeEgress("my-first-room", "speaker", $outputConfig);
        // dd($response);
        //TODO:: decode token 
        // $applicantId = 1;
        // $jobId = 1;
        // //TODO:: if Application and JOb exists and test is not already submitted
        // return view('test.attempt');
    }`

**Comment by ashwin-nath-m** [comment]
@hazhayder 

```php
$s3Upload = (new S3Upload())
            ->setAccessKey(config('linode.key'))
            ->setSecret(config('linode.secret'))
            ->setEndpoint(config('linode.endpoint'))
            ->setRegion(config('linode.region'))
            ->setBucket(config('linode.bucket'));
$tracks= (new AutoTrackEgress())
            ->setFilepath('livekit/test')
            ->setS3($s3Upload);
 $roomEgress =  (new RoomEgress())->setTracks($tracks);
 $opts = (new RoomCreateOptions())
            ->setName($roomName)
            ->setEmptyTimeout(15)
            ->setEgress($roomEgress);
$this->roomServiceClient->createRoom($opts);
```

And the error is

```
Expect integer. file":"....vendor/google/protobuf/src/Google/Protobuf/Internal/GPBUtil.php:111"

```

**Comment by hazhayder** [comment]
> @hazhayder
> 
> ```
> $s3Upload = (new S3Upload())
>             ->setAccessKey(config('linode.key'))
>             ->setSecret(config('linode.secret'))
>             ->setEndpoint(config('linode.endpoint'))
>             ->setRegion(config('linode.region'))
>             ->setBucket(config('linode.bucket'));
> $tracks= (new AutoTrackEgress())
>             ->setFilepath('livekit/test')
>             ->setS3($s3Upload);
>  $roomEgress =  (new RoomEgress())->setTracks($tracks);
>  $opts = (new RoomCreateOptions())
>             ->setName($roomName)
>             ->setEmptyTimeout(15)
>             ->setEgress($roomEgress);
> $this->roomServiceClient->createRoom($opts);
> ```
> 
> And the error is
> 
> ```
> Expect integer. file":"....vendor/google/protobuf/src/Google/Protobuf/Internal/GPBUtil.php:111"
> ```

Were you able to get around this error?

**Comment by ashwin-nath-m** [comment]
@p-delorme i have found an issue. created pr

**Comment by p-delorme** [comment]
Great Catch. I'll get that fix asap. Thanks @ashwin-nath-m

**Comment by p-delorme** [comment]
The PR has been merged.

**Comment by p-delorme** [comment]
A new release has been created. Feel free to test and report if this fixes the issue.
