### ISSUE TITLE
can php7 support this library

### ISSUE THREAD

**Issue by lxl518000** [agence104/livekit-server-sdk-php#2]
Thank you for your contribution. Can php7 use this library

**Comment by p-delorme** [comment]
Hi, the short answer is unfortunately, No. Some of the code uses PHP8 Syntax currently.

**Comment by kdeegan** [comment]
+1 supporting php7 would be great

**Comment by fender-hm** [comment]
> +1 supporting php7 would be great

I made a fork and downgrade code to support 7.0, you can use it.

**Comment by p-delorme** [comment]
Based on the number of request, I will try to release a PHP 7 version in the upcoming weeks.

**Comment by zionnite** [comment]
Thank you for doing this,

Please make it simple enough to get even without composer

**Comment by p-delorme** [comment]
Hello,

Sorry, based on the status and EOL of PHP7, I've decided to hold off on this feature request.

**Comment by p-delorme** [comment]
Closing this request, but any PRs are welcome.
