### ISSUE TITLE
 Issue with Removing Participants and Closing Rooms

### ISSUE THREAD

**Issue by riteshghimire9090** [agence104/livekit-server-sdk-php#20]
### Issue Description
We're encountering difficulties with removing all participants and closing rooms using PHP LiveKit. Despite attempting various methods, we haven't been able to achieve the desired outcome.

### Steps to Reproduce
1. Initialize a room using PHP LiveKit.
2. Add participants to the room.
3. Attempt to remove all participants programmatically.
4. Try to close the room using appropriate PHP LiveKit functions or methods.

### Expected Behavior
We expect that by removing all participants and closing the room, the session will end gracefully, freeing up resources and terminating any associated processes.

### Actual Behavior
The participants are not successfully removed, and the room closure process fails, leaving resources allocated and potentially causing issues with subsequent sessions.

We appreciate any assistance or insights into resolving this issue effectively.

**Comment by p-delorme** [comment]
Hi, I wasn't able to reproduce this error. Is this happening on Cloud or a self-hosted version?
