### ISSUE TITLE
Does Not Work with LiveKit Cloud

### ISSUE THREAD

**Issue by kornatzky** [agence104/livekit-server-sdk-php#23]
LiveKit cloud gives you a URL with wss scheme, e.g. wss://xxx.livekit.cloud 

Some API calls such as list rooms crash saying the scheme is not supported.

**Comment by p-delorme** [comment]
Hello @kornatzky,

The server SDK should be using https rather than wss, which is used only for a websocket connection.

Let me know if this fixes your issue.

**Comment by kornatzky** [comment]
Hello. It does not. The problem is that when you generate a project in LiveKit Cloud, you get a URL which is wss. There is no way to get a URL from the LiveKit Cloud which is https.

**Comment by p-delorme** [comment]
Hi,

I understand what you are saying although every server side calls are made to the same address although change url scheme from`wss://` to `https://`. That should resolve your issue.

I have just ran to full the full test suite on cloud and everything reported green.

Room Service Client (Agence104\LiveKit\Tests\RoomServiceClient)
 ✔ Create room
 ✔ List rooms
 ✔ Delete room
 ✔ Update room metadata
 ✔ List participants
 ✔ Get participant
 ✔ Remove participant
 ✔ Mute published track
 ✔ Update participant
 ✔ Update subscriptions
 ✔ Send data

Hope this helps.

**Comment by kornatzky** [comment]
This indeed solves the issue.
