### ISSUE TITLE
Webhook controller crashes with LiveKit cloud

### ISSUE THREAD

**Issue by kornatzky** [agence104/livekit-server-sdk-php#24]
When receiving the event participant_left, we get this exception:

 "exception": "[object] (Google\\Protobuf\\Internal\\GPBDecodeException(code: 0): Error occurred during parsing: Error occurred during parsing: disconnectReason is unknown. at /home/xxxx/yyy.zzz/vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php:1317)
[stacktrace]

**Comment by kornatzky** [comment]
Happens with this code:

```
namespace App\Http\Controllers;

use Illuminate\Http\Request;


use Agence104\LiveKit\WebhookReceiver;



class LiveKitWebhookController extends Controller
{



    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {

        $content = $request->getContent(); 
        $header = $request->header('authorization');
        $receiver = new WebhookReceiver(config('livekit.LIVEKIT_API_KEY'), config('livekit.LIVEKIT_API_SECRET'));
        $data = $receiver->receive($content, $header);
```

in the line: 

`$data = $receiver->receive($content, $header);`

**Comment by p-delorme** [comment]
This should be fixed in the latest version.
