### ISSUE TITLE
startRoomCompositeEgress method does not accept SegmentedFileOutput type

### ISSUE THREAD

**Issue by vlodel** [agence104/livekit-server-sdk-php#6]
Hello!

I'm trying to use the startRoomCompositeEgress method from the EgressServiceClient class to initiate a composite egress stream. However, it seems that the method does not accept the SegmentedFileOutput type as an output parameter, only EncodedFileOutput & StreamOutput are supported. Everything works fine when using an EncodedFileOutput type, but shouldn't the method also accept a SegmentedFileOutput as [here](https://docs.livekit.io/server/egress/room-composite/#stream-to-hls)?

Thank you for your assistance in resolving this issue. Please let me know if there's any further information or clarification needed.

**Comment by p-delorme** [comment]
It could be possible that the LiveKit Team brought modification on the Server side. Let look into this and I will get back to you. Could you provide me with the code you are trying to implement, if you wouldn't mind.

**Comment by p-delorme** [comment]
Okay, yes some changeswere brought up to the latest server.

I should have a fix up for you in a few hours.

**Comment by vlodel** [comment]
> It could be possible that the LiveKit Team brought modification on the Server side. Let look into this and I will get back to you. Could you provide me with the code you are trying to implement, if you wouldn't mind.

Here is an example of what I'm trying to do if you still need it:

```php
$esc = new EgressServiceClient(env('LIVEKIT_HOST'), env('LIVEKIT_API_KEY'), env('LIVEKIT_API_SECRET'));

$s3 = new S3Upload([
    "access_key" => env('AWS_ACCESS_KEY_ID'),
    "secret" => env('AWS_SECRET_ACCESS_KEY'),
    "region" => env('AWS_DEFAULT_REGION'),
    "bucket" => env('AWS_BUCKET'),
]);

$segmented_output = new SegmentedFileOutput();
$segmented_output->setFilenamePrefix('stream-');
$segmented_output->setS3($s3);

$esc->startRoomCompositeEgress($stream->key, 'single-speaker', $segmented_output);
```

**Comment by p-delorme** [comment]
A new version was just released which supports SegmentedFileOutput.

Please let me know if you are running issues.
