### ISSUE TITLE
Twirp dependency incompatible with newer dependencies

### ISSUE THREAD

**Issue by AimForNaN** [agence104/livekit-server-sdk-php#7]
```
twirp/twirp v0.8.1 requires psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1]
but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match.
```

**Comment by p-delorme** [comment]
The package does not provide a lock file. Maybe this is specific to your project?

**Comment by truefusion** [comment]
I'm using Laravel 10 which has dependencies that require newer versions of `psr/http-message`. I was able to write my own classes to work around the issue without depending on twirp. Just wanted to let the issue be known.

**Comment by echo-LuGuang** [comment]
I also encountered this problem

laravel10

**Comment by p-delorme** [comment]
A new version has been released. 

Feel free to test and report if this fixes the issue.

**Comment by p-delorme** [comment]
I'm closing this Issue, but please reopen or create another issue if required.
