### ISSUE TITLE
the version is old, some features have not been updated

### ISSUE THREAD

**Issue by wzJun1** [agence104/livekit-server-sdk-php#9]
eg: canUpdateOwnMetadata

eg: hook parse

**Comment by p-delorme** [comment]
You can expect an update soon, matching the latests SDKs.

**Comment by dgillier** [comment]
Hello, any news on the update ?

Thanks!

**Comment by p-delorme** [comment]
Hello @dgillier,

Sorry for the delay, but yes. Expect an update within the upcoming days.

**Comment by p-delorme** [comment]
A new version was just released with updated Protocol. 

Feel free to test and report any issues.
